@extends('components.back.layout.back')

@section('content')
<main class="p-6 overflow-y-auto">
    <!-- Header -->
    <div class="flex justify-between items-center mb-6">
        <h1 class="text-3xl font-bold hidden lg:block">Test Test1</h1>
    </div>

    <!-- Dashboard Widgets -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
        <div class="bg-green-500 text-white p-6 rounded-lg shadow-lg flex justify-between items-center">
            <div>
                <p class="text-sm">Approved properties</p>
                <p class="text-3xl font-bold">1</p>
            </div>
            <i class="ri-checkbox-circle-line text-4xl opacity-50"></i>
        </div>
        <div class="bg-yellow-500 text-white p-6 rounded-lg shadow-lg flex justify-between items-center">
            <div>
                <p class="text-sm">Pending approve properties</p>
                <p class="text-3xl font-bold">0</p>
            </div>
            <i class="ri-time-line text-4xl opacity-50"></i>
        </div>
        <div class="bg-red-500 text-white p-6 rounded-lg shadow-lg flex justify-between items-center">
            <div>
                <p class="text-sm">Rejected properties</p>
                <p class="text-3xl font-bold">0</p>
            </div>
            <i class="ri-edit-line text-4xl opacity-50"></i>
        </div>
    </div>

    <!-- Activity Logs -->
    <div class="bg-white rounded-lg shadow p-6">
        <h2 class="text-xl font-semibold mb-4">Activity Logs</h2>
        <ul id="activityLogs">
            <!-- Logs dynamically generated by JS -->
        </ul>
    </div>
</main>

<script>
    // Activity Logs
    const activityLogs = [{
            id: 1,
            description: "Updated property 'Sunshine Villa'",
            ipAddress: "192.168.1.1"
        },
        {
            id: 2,
            description: "Added new property listing",
            ipAddress: "192.168.1.2"
        },
    ];
    const logsContainer = document.getElementById('activityLogs');

    function renderLogs() {
        if (activityLogs.length === 0) {
            logsContainer.innerHTML = '<p class="text-gray-500">No activity logs available</p>';
        } else {
            logsContainer.innerHTML = activityLogs.map(log => `
                    <li class="flex items-center py-3 border-b last:border-b-0">
                        <i class="ri-time-line mr-3 text-gray-400"></i>
                        <div>
                            <p class="text-sm">${log.description}</p>
                            <p class="text-xs text-gray-500">(${log.ipAddress})</p>
                        </div>
                    </li>
                `).join('');
        }
    }

    renderLogs();

</script>
@endsection


